version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: bot-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
